Feature/get stock info
team9-be/stocker-be pull request #47
Opened 2023-08-29 07:36 UTC by tjsdn9803

issue

util/YesterdayPrice의 getYesterdayLastPrice를 @Cachable을 사용하여 캐시에 저장하도록 변경
상승률, 하락률 랭킹 조회 시 cache aside 전략으로 getYesterdayLastPrice 메소드 호출 시 모든 종목의 어제자 최종 가격을 캐쉬에 저장
해당 캐시는 상승률, 하락률 조회, 주식 상세 조회시 현재가와 어제 가격 비교 등에 사용 
또한 자정에 스케쥴링을 사용하여 cache warming을 통해 미리 캐쉬에 모든 종목의 YesterdaylastPrice와 거래량,상승률,하락률 상위 종목의 데이터를 캐시로 저장하도록 변경

이에따른 랭킹서비스 리팩토링 및 캐쉬 설정 변경, 거래내역이 없는 종목에 대한 예외 처리

2023-08-29 08:11 UTC, downside154 requested changes

2023-08-29 08:11 UTC, downside154 commented on src/main/java/com/project/stocker/configure/RedisConfig.java
로직 구현 하시느라 고생하셨습니다! 
작성하신 부분 외에도 해당 파일의 코드가 정리 + 가독성이 필요한 것 같습니다. 
혹시 아래 부분처럼 정리 하는 것에 대해 어떻게 생각하시나요?
(급하게 작성하느라 오타/오류 있음 주의)

```java
package com.project.stocker.configure;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.cache.RedisCacheConfiguration;
import org.springframework.data.redis.cache.RedisCacheManager;
import org.springframework.data.redis.cache.RedisCacheWriter;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.serializer.StringRedisSerializer;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

@Configuration
@EnableCaching
public class RedisConfig {

    private final String host;
    private final int port;

    public RedisConfig(@Value("${spring.data.redis.host}") String host,
                       @Value("${spring.data.redis.port}") int port) {
        this.host = host;
        this.port = port;
    }

    @Bean
    public RedisCacheManager redisCacheManager(RedisConnectionFactory redisConnectionFactory) {
        RedisCacheConfiguration cacheConfiguration = createCacheConfiguration(Duration.ofHours(1));

        Map<String, RedisCacheConfiguration> cacheConfigurations = new HashMap<>();
        cacheConfigurations.put("yesterdayLastPrice", createCacheConfiguration(Duration.ofHours(24)));
        cacheConfigurations.put("top10ByTradeIncrease", createCacheConfiguration(Duration.ofHours(24)));
        cacheConfigurations.put("top10ByTradeDecrease", createCacheConfiguration(Duration.ofHours(24)));
        cacheConfigurations.put("top10ByTradeVolume", createCacheConfiguration(Duration.ofHours(24)));

        return RedisCacheManager.builder()
                .cacheWriter(RedisCacheWriter.nonLockingRedisCacheWriter(redisConnectionFactory))
                .cacheDefaults(cacheConfiguration)
                .withInitialCacheConfigurations(cacheConfigurations)
                .build();
    }

    private RedisCacheConfiguration createCacheConfiguration(Duration ttl) {
        return RedisCacheConfiguration.defaultCacheConfig()
                .entryTtl(ttl)
                .disableCachingNullValues();
    }

    @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        return new LettuceConnectionFactory(host, port);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate() {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setValueSerializer(new StringRedisSerializer());
        redisTemplate.setConnectionFactory(redisConnectionFactory());
        return redisTemplate;
    }
}

```

2023-08-29 08:11 UTC, downside154 commented on src/main/java/com/project/stocker/controller/CrawlingController.java
크롤링 부분을 Spring Batch 사용해서 개선해보는 것도 괜찮을 것 같아요!

2023-08-30 01:05 UTC, powerlife145 approved these changes
goodd

2023-08-30 06:38 UTC, tjsdn9803 commented on src/main/java/com/project/stocker/configure/RedisConfig.java
수정하여 올렸습니다~

2023-08-30 06:41 UTC, tjsdn9803 commented on src/main/java/com/project/stocker/controller/StockController.java
> +    }
ResponseEntity활용하여 완료되었다는 문구를 응답해주도록 변경하였습니다.
또한 주식 상세 조회 api또한 우선 통일하려 ResponseEntity를 사용하여 응답하도록 변경하였습니다.
하지만 이 부분은 뷰페이지를 만들면서 수정될 듯 합니다

2023-08-30 06:43 UTC, tjsdn9803 commented on src/main/java/com/project/stocker/util/JsoupCrawling.java
> +                Connection conn = Jsoup.connect(TRADE_URL_BASE + "code=" + stock.getCode() + "&thistime=20230828162200&page=" + i);
이전에 현재시간에 맞춰서 하루전이나 며칠전의 시간을 파라미터로 넣으려 했으나 
공휴일과 주말에 해당하는 시간 입력 시 거래 정보를 얻을 수 없는 오류 떄문에 우선 다음과 같이 해놓았습니다.
이 부분도 뷰페이지가 어느정도 완성되면 개선시켜보겠습니다.

2023-08-30 08:58 UTC, merged